### ISSUE TITLE
ImageUrlRewriter incorrect url

### ISSUE THREAD

**Issue by dapriett** [wro4j/wro4j#1008]
Hello,

I'm seeing a bug with the `ImageUrlRewriter.rewrite` method when using the `CSSUrlRewritingProcessor`

https://github.com/wro4j/wro4j/blob/master/wro4j-core/src/main/java/ro/isdc/wro/model/resource/processor/support/ImageUrlRewriter.java#L103

```
    if (UrlUriLocator.isValid(cssUri)) {
      final String computedCssUri = ServletContextUriLocator.isValid(imageUrl) ? computeCssUriForExternalServer(cssUri)
          : cssUri;
      return computeNewImageLocation(computedCssUri, imageUrl);
    }
    if (ClasspathUriLocator.isValid(cssUri)) {
      final String proxyUrl = context.proxyPrefix + computeNewImageLocation(cssUri, imageUrl);
      final String contextRelativeUrl = prependContextPath(imageUrl);
      //final String contextRelativeUrl = context.contextPath + imageUrl;
      // leave imageUrl unchanged if it is a servlet context relative resource
      return (ServletContextUriLocator.isValid(imageUrl) ? contextRelativeUrl : proxyUrl);
    }
```

I believe the ClasspathUriLocator.isValid block should be before the UrlUriLocator.isValid(cssUri) block.  When the `cssUrl` is `classpath:...` then `UrlUriLocator.isValid(cssUri)` comes back as `true`.  Either that, or UrlUriLocator.isValid should ignore classpath urls.

The result is my css urls are getting rewriting as `url(classpath:..)` and not `url(/wro/?wroAPI=wroResources&id=classpath:..)`

**Comment by alexo** [comment]
Could you create a test which proves the bug?

**Comment by dapriett** [comment]
I believe the issue is because I'm using Spring-boot.  They must register the protocol "classpath:" somewhere, so `new URL("classpath:/...")` is actually a valid url, causing `UrlUriLocator.isValid` to be true.  

I checked the tests in `TestImageUrlRewriter`, and that is correctly returning false for `UrlUriLocator.isValid` for classpath urls

**Comment by alexo** [comment]
What do you suggest in that case? Should we do something to fix the problem or just close this issue as invalid resolution?

**Comment by dapriett** [comment]
I created a pull request - just moved the Classpath check before Url check

**Comment by alexo** [comment]
@dapriett thanks, I'll merge it soon.
