### ISSUE TITLE
allow the cssImport pre processor to import with webjars locator

### ISSUE THREAD

**Issue by dodgex** [wro4j/wro4j#1014]
Hey there,

currently the CssImportPreProcessor rewrites imports like `@import "webjar:/bootstrap/less/bootstrap.less";` to this resource uri `classpath:wro/less/webjar:/bootstrap/less/bootstrap.less`. The issue is [here](https://github.com/wro4j/wro4j/blob/1d0b19be46952917e4ef0727e0bdb8d15d489e09/wro4j-core/src/main/java/ro/isdc/wro/model/resource/processor/impl/css/AbstractCssImportPreProcessor.java#L193). the `UrlUriLocator.isValid(importUrl)` call tries to `new URL(uri);` but that throws an exeption as `webjar:/` is no valid prefix here. not even `classpath:/` is allowed as a workaround as it gets prefixed with `classpath:wro/less/` too. :(

as it would be nice to be able to import resources from webjars (and other locators too) i digged into the code to see if there is a fix for that.

after some time i found that there is a pretty easy fix.

there are two solutions:
1) replace the `UrlUriLocator.isValid(importUrl)` with `uriLocatorFactory.getInstance(importUrl) != null`
or
2) add ` || uriLocatorFactory.getInstance(importUrl) != null` to the condition.

i'll open a PR with the first solution.

**Comment by alexo** [comment]
This should not be the issue since 1.8.0 release. There is a new [webjars locator](https://github.com/wro4j/wro4j/blob/1.8.x/wro4j-extensions/src/main/java/ro/isdc/wro/extensions/locator/WebjarsUriLocator.java) which uses a different prefix (**webjars/** instead of **webjar:**) and locates the webjar resources using webjar servlet.

**Comment by dodgex** [comment]
i have a custom webjar importer that supports leaving the version out of the path. it can map e.g. `/bootstrap/css/bootstrap.min.css` to `/bootstrap/3.3.6/css/bootstrap.min.css`

also this fix supports any locator that is available. as mentioned, you can't even do `classpath:/this/is/not/where/other/wro4j/files/are/style.css` currently due to the Url test.

**Comment by alexo** [comment]
We could apply this fix for situations when the old locator is used, however I would recommend using the new webjars locator which avoid this issue ...

**Comment by dodgex** [comment]
the new webjars locator avoids the issue for webjars. but not for *insert any custom locator here* when they use `abc:` instead of `abc/`. and at least i prefer the `:` for the prefix as can not be mistaken with an actual folder.

**Comment by dodgex** [comment]
if you have worries with the proposed fix. i can refactor my custom locator to use the `/` so it should like your new `webjars` locator. I'm not a big fan of this solution but it is up to you to decide if you like the proposed fix or not. :)

**Comment by alexo** [comment]
Please, provide the PR and it will be merged. 
Thanks!

**Comment by dodgex** [comment]
what PR do you mean exaclty? i fixed this issue with PR https://github.com/wro4j/wro4j/pull/1015

**Comment by alexo** [comment]
Could you add a couple of unit tests as well? Thanks!

**Comment by dodgex** [comment]
@alexo i opened a new PR (against `1.8.x` branch instead of master) and added a test. i hope it is okay this way.

**Comment by alexo** [comment]
Thanks a lot. I'll merge tomorrow.
On Apr 25, 2016 11:34 PM, "Kay-Uwe Janssen" <notifications@github.com>
wrote:
>
> @alexo i opened a new PR (against 1.8.x branch instead of master) and
added a test. i hope it is okay this way.
