### ISSUE TITLE
GoogleClosureCompressorProcessor CompilerOptions not settable

### ISSUE THREAD

**Issue by cnsgithub** [wro4j/wro4j#1031]
(Sorry i opened the issue at the old alexo repo) - so i'm creating it here too:
--
Hi, lets assume i want to set a Compiler option

`
                        CompilationLevel cl = CompilationLevel.SIMPLE_OPTIMIZATIONS ;
			CompilerOptions options = new CompilerOptions();
			options.setLanguageIn(LanguageMode.ECMASCRIPT5);
			cl.setOptionsForCompilationLevel(options);
`

It doesnt seem to work as the constructor always uses a predefined option set from the pool 

`
optionsPool = new ObjectPoolHelper<CompilerOptions>(new ObjectFactory<CompilerOptions>() {
      @Override
      public CompilerOptions create() {
        return newCompilerOptions();
      }
    });
`
 
`
final CompilerOptions compilerOptions = optionsPool.getObject();

`

Workaround used now:

`
 public CustomGoogleClosureCompressorProcessor(final CompilationLevel compilationLevel, final CompilerOptions options) {
		 
		 try{
		    Validate.notNull(compilationLevel);
		    /**
		     * Using pool to fix the threadSafety issue. See <a
		     * href="http://code.google.com/p/closure-compiler/issues/detail?id=781">issue</a>.
		     */
		    ObjectPoolHelper<CompilerOptions> optionsPool = new ObjectPoolHelper<CompilerOptions>(new ObjectFactory<CompilerOptions>() {
		      @Override
		      public CompilerOptions create() {
		        return options;
		      }
		    });
		    
		    Field optionsPool_f = this.getClass().getSuperclass().getDeclaredField("optionsPool");
		    optionsPool_f.setAccessible(true);
		    optionsPool_f.set(this, optionsPool);
		    
		    Field compilationLevel_f = this.getClass().getSuperclass().getDeclaredField("compilationLevel");
		    compilationLevel_f.setAccessible(true);
		    compilationLevel_f.set(this, compilationLevel);
		 }catch(Exception e){
			 e.printStackTrace();
		 }
		  }
`

Or am i doing something wrong?  Thanks

**Comment by alexo** [comment]
@cnsgithub The compiler options is initialized in newCompilerOptions() method. By overriding this method, you can control the options you want to be used by the compiler.

Let me know if that helps.

**Comment by cnsgithub** [comment]
Hi, Thanks - ok i understand now, however this usage is really hard to grasp. Wouldn't it be better to have a public setter on it? At least some usage into the javadoc should be made imo.

Anyway this is the usage i'm using now for a reference:

`
	GoogleClosureCompressorProcessor closureProcessor = new GoogleClosureCompressorProcessor(CompilationLevel.SIMPLE_OPTIMIZATIONS) {
			    @Override
			    protected CompilerOptions newCompilerOptions(){
			    	CompilerOptions options = new CompilerOptions();
			    	options.setLanguageIn(LanguageMode.ECMASCRIPT5);
			    	return options;
		        }   
			};
			closureProcessor.process(in, out);

`

**Comment by alexo** [comment]
I agree with you that it is not that straightforward for a newcomer. 
If you believe the documentation can be improved, a Pull Request is welcome..
