### ISSUE TITLE
WRO4J

### ISSUE THREAD

**Issue by nimidroids** [wro4j/wro4j#1049]
I have spring mvc+ boot + wro4j application.

how to load all wro4j contains css and js files on server start.

currently, wro model calls on request . so sometimes css and js does load properly for requested page.

**Comment by alexo** [comment]
I'm not sure I understand the question, but I'll try to describe what is the intended behavior:

Runtime solution - the resources are processed lazily after the first request. Assuming you have defined 100 groups and only one is requested, the remaining 99 won't be processed. 

Build time solution - the resources are processed when the application is built. You are in control of defining what groups should be generated (either all of them or only a subset enumerated in configuration).

If what you need is to have all resources available during application startup, then probably using a build-time solution (maven plugin) is the best suited for you. Alternatively, you could use the runtime solution and explicitly perform requests for all the groups after application startup.

Let me know if this helps.

Cheers,
Alex

**Comment by ppodgorsek** [comment]
Added @alexo 's explanation to the project's README. Closing this ticket due to inactivity.
