### ISSUE TITLE
Fail to minify angularjs 1.x JS files

### ISSUE THREAD

**Issue by indusbull** [wro4j/wro4j#1057]
I am using WR4J 1.8 to bundle and minify my angularjs files at runtime. The files are bundled together but they are not minimized (means it still has whitespaces in it) when served to browser. I am not sure what I am doing wrong. 

Below is my config in web.xml:
    `<filter>
	  <filter-name>WebResourceOptimizer</filter-name>
	  <filter-class>ro.isdc.wro.http.WroFilter</filter-class>	 
	</filter>
     <filter-mapping>
	  <filter-name>WebResourceOptimizer</filter-name>
	  <url-pattern>/resource/bundles/*</url-pattern>
    </filter-mapping>`

Groups in wro.xml:

`<group name="dashboard-main">
     <js>/includes/dashboard/db-oss-app.js</js>
    <js>/includes/dashboard/db-dast-app.js</js>
    <js>/includes/dashboard/db-sast-app.js</js>
    <js>/includes/dashboard/db-overview-app.js</js>
    <js>/includes/dashboard/db-reports-app.js</js>
    <js>/includes/dashboard/db-app.js</js>
 </group>`

	
And this is how I include bundle in my JSP:
<script src='/resource/bundles/dashboard-main.js' type='text/javascript'></script>

**Comment by alexo** [comment]
In order to apply any processors, you should add more configs, otherwise, only bundling is applied. Please take look on the available [examples](https://github.com/wro4j/wro4j-examples/blob/master/wro4j-bootstrap-runtime/src/main/webapp/WEB-INF/wro.properties) on how to provide custom configs.

**Comment by indusbull** [comment]
I might have missed this info but when I followed 3 steps [tutorial]( http://wro4j.github.io/wro4j/), it seems like minification and bundling is done by default when you complete all steps. It doesn't say that I need to explicitly set jsMin & cssMin in properties. Thanks for clarifying it. 

Nifty tool in between!!
