### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by ronvanpol** [wro4j/wro4j#1068]
I'm wondering whether or not this project is still being maintained. I am using the maven wro4j plugin for quite some time and would like to upgrade to java 9+ (11 at the moment). This plugin won't work (see issue [https://github.com/wro4j/wro4j/issues/1039](1039)). The last commit is well over a year old. It seems like this project is abandoned.

**Comment by alexo** [comment]
Hi @ronvanpol .
I wouldn't say it is abandoned, rather it is not actively maintained. 
I'll take a look on the reported issue and will provide an ETA as soon as I can.
