### ISSUE TITLE
Cors headers overridden by ResourceBundleProcessor

### ISSUE THREAD

**Issue by ppodgorsek** [wro4j/wro4j#1075]
When using Spring Security, the CorsFilter adds `Vary` headers to the response.
Unfortunately, instead of appending headers, the ResourceBundleProcessor replaces all existing `Vary` headers in its `serveProcessedBundle()` method. Instead, it should simply add any new headers.

**Comment by ppodgorsek** [comment]
This bug has been fixed and merged.

**Comment by alexo** [comment]
@ppodgorsek Thanks for your contribution.
