### ISSUE TITLE
Add wro4j-maven-plugin:help goal

### ISSUE THREAD

**Issue by sewe** [wro4j/wro4j#1088]
Most Maven plugins provide a `help` goal [(automatically generated by the `maven-plugin-plugin`)](https://maven.apache.org/plugin-tools/maven-plugin-plugin/examples/generate-help.html). It would hence be nice if the `wro4j-maven-plugin` could also provide this goal.

**Comment by ppodgorsek** [comment]
Added in PR #1156.
