### ISSUE TITLE
Unable to build project in eclipse after eclipse migration from 2020-06 to 2020-09

### ISSUE THREAD

**Issue by arnaud-quiblier** [wro4j/wro4j#1092]
Hello,

After eclipse migration from 2020-06 (4.16) to 2020-09 (4.17), maven project using wro4j-maven-plugin:1.8.0 no longer unable to build.
Only the internal m2e refresh fails.
A call to the goal wro4j:run through a Maven Build launcher builds succesfully.
A call to the goal wro4j:run through Maven CLI builds succesfully too.

So I think it's related to wro4j-maven-plugin / m2e integration.
I think it's related more precisely to java version used to run the plugin internally.
Indeed, Eclipse 2020-09 now require java 11+ (https://wiki.eclipse.org/Eclipse/Installation#Eclipse_4.17_.282020-09.29)

I attach a partial stacktrace from Eclipse Error view.
[partial_stacktrace.txt](https://github.com/wro4j/wro4j/files/5475891/partial_stacktrace.txt)

In order to repoduce, I add a minimal maven project.
[wro4j.zip](https://github.com/wro4j/wro4j/files/5475901/wro4j.zip)

Environment before eclipse migration :
- Eclipse 2020-06 with 2 jdks installed : 1.8.0_u66 & 11.03.3+7
- m2e 1.16.0.20200610-1735
- m2e-connectore-wro4j 1.1.0.201406251020

Environment after eclipse migration :
- Eclipse 2020-09 with 2 jdks installed : 11.03.3+7 & 1.8.0_u66
- m2e 1.16.1.20200710-1008
- m2e-connectore-wro4j 1.1.0.201406251020

Maven project :
- maven.compiler.source & maven.compiler.target : 1.8
- wro4j-maven-plugin : 1.8.0

Thanks,
Arnaud

**Comment by ppodgorsek** [comment]
The latest version of the Wro4j project on the `master` branch now relies on Java 17. Could you let me know if this issue still occurs please?

**Comment by arnaud-quiblier** [comment]
@ppodgorsek Thank you for the update.
But we no longer use wro4j-maven-plugin, so I won't be able to test this new version.
Feel free to close this ticket.
