### ISSUE TITLE
The link in the project description is not valid

### ISSUE THREAD

**Issue by likui628** [wro4j/wro4j#1133]
https://wro4j.github.com/wro4j/

![image](https://user-images.githubusercontent.com/90845831/190889348-30243a53-1124-4e25-b4ae-7aa03c97b780.png)

**Comment by marcelstoer** [comment]
Should point to https://wro4j.github.io/wro4j/ instead as described in the error message.

**Comment by ppodgorsek** [comment]
The link has been updated.
