### ISSUE TITLE
Test Failure observed due to flakiness.

### ISSUE THREAD

**Issue by java-codehunger** [wro4j/wro4j#1134]
I ran this test 10,000 times in normal settings and got the following failures for many times.

[INFO] Running ro.isdc.wro.model.group.processor.TestPreProcessorExecutor
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 79.4 s <<< FAILURE! - in ro.isdc.wro.model.group.processor.TestPreProcessorExecutor
[ERROR] preProcessingInParallelIsFaster(ro.isdc.wro.model.group.processor.TestPreProcessorExecutor)  Time elapsed: 79.329 s  <<< FAILURE!
java.lang.AssertionError: 13825  > 13324 + 10659.2
	at ro.isdc.wro.model.group.processor.TestPreProcessorExecutor.preProcessingInParallelIsFaster(TestPreProcessorExecutor.java:280)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestPreProcessorExecutor.preProcessingInParallelIsFaster:280 13825  > 13324 + 10659.2
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

I run the following command 10,000 times without modifying anything.

mvn test -pl wro4j-core -Dtest=ro.isdc.wro.model.group.processor.TestPreProcessorExecutor#preProcessingInParallelIsFaster

Environment(please complete the following information):
I ran the test on an Ubuntu 20.04 LTS machine using OpenJDK 1.8.0_312.

**Comment by ppodgorsek** [comment]
The delay has been adjusted in PR #1142.
