### ISSUE TITLE
Migrate to Jakarta

### ISSUE THREAD

**Issue by pbelbin** [wro4j/wro4j#1135]
Ummmm, anyone migrating their code over to the Jakarta namespace so that they can use the new versions of EE?

I'm trying to do that, while also using wro4j, and find that there are complaints about the filter needing javax classes, which don't exist in the new Jakarta-flavor of EE.

Does anyone already have something that works with say, Payara server 2023.1 (Jakarta EE 10)?  If so, please point me at it!

Thank you in advance!

**Comment by sebint** [comment]
Hi @pbelbin found any solutions?

**Comment by ppodgorsek** [comment]
The main issue here was that the Spring Framework hadn't migrated to Jakarta yet. With the recent release of Spring 6, we should now be able to do the switch.
I aim to work on upgrading the dependencies in the next week or two.

**Comment by anatoliy-balakirev** [comment]
Hi @ppodgorsek Any news on this? Do you need some help maybe?

**Comment by ppodgorsek** [comment]
Sorry for the delay, I finally finished working on it and merged it as part of PR #1141.
Due to the breaking change, this will probably deserve Wro4j jumping to version 2.

**Comment by ppodgorsek** [comment]
Version 2.0.0 has been published today.

**Comment by pbelbin** [comment]
thank you much!

**Comment by anatoliy-balakirev** [comment]
@ppodgorsek great news, thank you very much!
