### ISSUE TITLE
Upgrade commons-io from 2.8.0 to 2.11.0

### ISSUE THREAD

**Issue by ataillefer** [wro4j/wro4j#1136]
In our project, we're relying on the latest wro4j version 1.10.1 and commons-io:commons-io 2.8.

We've tried to upgrade commons-io in our project to the latest version, 2.11.
Yet, it seems that some implementation changes in `org.apache.commons.io.FileUtils#listFiles` (see the [Apache Commons IO Release Notes](https://commons.apache.org/proper/commons-io/changes-report.html#a2.11.0) for 2.9.0) are breaking the existing behavior of [ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator#findMatchedFiles](https://github.com/wro4j/wro4j/blob/v1.10.1/wro4j-core/src/main/java/ro/isdc/wro/model/resource/locator/wildcard/DefaultWildcardStreamLocator.java#L136):

```
private Collection<File> findMatchedFiles(final WildcardContext wildcardContext)
    throws IOException {
  validate(wildcardContext);

  // Holds a set of all files (also folders, not only resources). This is useful for wildcard expander processing.
  final Set<File> allFiles = new TreeSet<File>(ALPHABETIC_FILE_COMPARATOR);
  final IOFileFilter fileFilter = createWildcardCollectorFileFilter(wildcardContext, allFiles);
  FileUtils.listFiles(wildcardContext.getFolder(), fileFilter, getFolderFilter(wildcardContext.getWildcard()));

  triggerWildcardExpander(allFiles, wildcardContext);

  return allFiles;
}
```

With commons-io:2.11, when calling `findMatchedFiles` with a `wildcardContext` built from:
- uri: `"file:/my/project/path/target/test-classes/css/*"`
- folder: `"/my/project/path/target/test-classes/css/"`

the  method returns an empty `allFiles` Set, leading to the stack trace below:

```
java.io.IOException: No resource found for wildcard: *
	at ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator.triggerWildcardExpander(DefaultWildcardStreamLocator.java:191)
	at ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator.findMatchedFiles(DefaultWildcardStreamLocator.java:145)
	at ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator.locateStream(DefaultWildcardStreamLocator.java:94)
	at ro.isdc.wro.model.resource.locator.UrlUriLocator.locate(UrlUriLocator.java:81)
```
With commons-io 2.8 and the same call, the resulting `allFiles` Set is not empty. Just after the call to `FileUtils.listFiles()`, it contains the CSS file located in `/my/project/path/target/test-classes/css/myTestFile.css`.

Would you consider upgrading to commons-io:2.11?

Thanks

**Comment by guillaume-alvarez** [comment]
The issue happens because the method called in `WildcardFileFilter` is no longer `accept(File)` but `accept(Path,BasicFileAttributes)`.

So the code in `DefaultWildcardStreamLocator` is no longer called:
```
  private IOFileFilter createWildcardCollectorFileFilter(final WildcardContext wildcardContext, final Collection<File> allFiles) {
    notNull(wildcardContext);
    notNull(allFiles);
    return new WildcardFileFilter(wildcardContext.getWildcard()) {
      @Override
      public boolean accept(final File file) {
        final boolean accept = super.accept(file);
        if (accept) {
          LOG.debug("\tfound resource: {}", file.getPath());
          allFiles.add(file);
        }
        return accept;
      }
    };
  }
```

It would be better to rewrite `DefaultWildcardStreamLocator.findMatchedFiles` to use `FileUtils.listFiles` return value instead of relying on a side-effect of the filter check.
