### ISSUE TITLE
wro4j Gradle plugin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#404]
```
Create gradle plugin for wro4j. 

Useful links:

http://www.gradle.org/docs/current/userguide/userguide_single.html#custom_plugin
s
https://github.com/bmuschko/gradle-gaelyk-plugin
```

Original issue reported on code.google.com by `alex.obj...@gmail.com` on 27 Mar 2012 at 8:14

**Comment by IlyaAI** [comment]
Hi,
Who interesting, I'm working on [Wro4J Gradle Plugin](https://github.com/IlyaAI/wro4j-gradle-plugin) now.

**Comment by alexo** [comment]
@IlyaAI glad to hear that. Thanks for sharing it. If you want, I could add your project under wro4j github organization for better visibility.

**Comment by IlyaAI** [comment]
Great! I write you back when I'll be ready. Thanks.

**Comment by IlyaAI** [comment]
Hi Alex!
I've released [Wro4J Gradle Plugin 1.7.9.Beta2](https://github.com/IlyaAI/wro4j-gradle-plugin/tree/1.7.9.Beta2).
As you suggested above, please move my project under wro4j organization.

**Comment by alexo** [comment]
@IlyaAI you've been granted a role in wro4j github organization. You should be able now to migrate the project to a new location. Let me know if you have any issues. Thanks!

**Comment by IlyaAI** [comment]
Now repository available at https://github.com/wro4j/wro4j-gradle-plugin
Thanks.
