### ISSUE TITLE
Not able to execute the application in Linux mechin

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#799]
```
1. I am using wro4j-1.6.3 version in windows and linux
2. I have implemented wro4j for my application, it is working fine with Windows 
mechin in my local system.Where as same war file i have uploaded in jboss 
server which is exist in Linux mechin, i am getting error like path of the 
minfied compressed file is not founding there. Please help on the same.

PFA for your rererence.

```

Original issue reported on code.google.com by `ramajaga...@gmail.com` on 9 Oct 2013 at 6:27

Attachments:
* [wro_issue.png](https://storage.googleapis.com/google-code-attachments/wro4j/issue-799/comment-0/wro_issue.png)

**Comment by alexo** [comment]
Not enough details to understand the problem. Closing this issue with invalid resolution.
