### ISSUE TITLE
Make wro.xml file name configurable

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#913]
```
I use wro with spring injection and I'm unable to have several separate wro 
configurations for different environments because there is no way to configure 
wro.xml file name.
```

Original issue reported on code.google.com by `asho...@gmail.com` on 30 Dec 2014 at 10:09

**Comment by marcelstoer** [comment]
Easy work-around:
- [extend BaseWroManagerFactory](https://code.google.com/p/wro4j/wiki/ExtendingGroupExtractor#Extend_the_class_and_override_the_newGroupExtractor_method_to_re)
- override `newModelFactory`
- provide your own `WroModelFactory` (extending `XmlModelFactory`) with a custom `getDefaultModelFilename` implementation

**Comment by alexo** [comment]
@marcelstoer  Thanks for update.

I'll close this issue with WONTFIX resolution. Since it has a workaround.
