### ISSUE TITLE
Migrate documentation from google code

### ISSUE THREAD

**Issue by alexo** [wro4j/wro4j#931]
Since google code is closing, the documentation should be migrated as well. 
The documentation should be located in the same location as the source code. The benefit would be:
- centralized location of the documentation
- documentation can be tagged and released as part of each release.
- the documentation can be easily searchable.

The new documentation home will be: http://wro4j.readthedocs.org/

**Comment by marcelstoer** [comment]
> The documentation should be located in the same location as the source code.

Exactly, then why don't you use [GitHub pages](https://pages.github.com/#project-site) which would allow you to keep the docs in the same repository as the code (in the `gh-pages` branch)? Or use the GitHub wiki?

**Comment by alexo** [comment]
@marcelstoer Read the docs build the documentation from github source location. The big advantage over using gh-pages branch or GitHub wiki, is that the documentation is versioned automatically by each release.

**Comment by marcelstoer** [comment]
> "Readthedocs" builds the documentation from github source location.

Oh, sorry, forgive my ignorance. I only just learned about that service. Sounds fantastic.

**Comment by alexo** [comment]
@marcelstoer  not a problem :)... Here is a sample branch containing partly migrated documentation: http://wro4j.readthedocs.org/en/docs/   The branch where the migration is done currently is called "docs", but it will be named as the version (ex: 1.7.8) when it is ready and new version is released.
