### ISSUE TITLE
Can I use import inside selector?

### ISSUE THREAD

**Issue by psychobolt** [wro4j/wro4j#936]
Hi, can I use the following code to wrap my import css in a namespace?

.bootstrap {
    @import "bootstrap.less";
}

or

.bootstrap {
    @import (less) "bootstrap.css";
}

**Comment by alexo** [comment]
As long as this is a valid less syntax and you are using less4j it should work.

**Comment by psychobolt** [comment]
Hi, I fixed my problem. I had configured processors incorrectly:

preProcessors=lessCssImport
postProcessors=lessCss, less4j

should be

preProcessors=less4j, lessCssImport
postProcessors=lessCss
