### ISSUE TITLE
Allow easy extension of XmlModelFactory

### ISSUE THREAD

**Issue by marcelstoer** [wro4j/wro4j#938]
Nearly all methods in `XmlModelFactory` are private. I'm not sure this is intentional but it makes this class de-facto final as there are no useful extension points. I suggest you make most of those private methods protected (e.g. all `parse` and `process` methods.)

My use case: rather than setting the `minimize` attribute on a resource I want to check if it's name ends in `*.min.js`, `*-min.js`, etc. and set that flag automatically. Right now I'd have to copy-paste the entire `XmlModelFactory` class.

For reference...I think I'd use something like the following regex

    .*[-\.](min|pack)\.(js|css)

![Regular expression visualization](https://www.debuggex.com/i/Ra1yiMx7en3mdU2e.png)

[Debuggex Demo](https://www.debuggex.com/r/Ra1yiMx7en3mdU2e)

**Comment by alexo** [comment]
There was no use-case like the one described by you until now. In theory, you can build a custom model factory just implementing the WroModelFactory interface. Marking a resource as minimized based on its name does make sense. 

Rather then making some of the private methods protected, I would rather create new methods (with protected modifier), which are responsible for building a resource (or a group) based on encountered Element. This should allow easily extending it and adapting for required use-case. Is that ok?

**Comment by marcelstoer** [comment]
> In theory, you can build a custom model factory just implementing the WroModelFactory interface.

Sure, but I want to re-use the existing XML processing code.

> If you are willing to contribute, it could be released sooner.

Definitely, I just don't really understand how you'd structure the new methods. To further develop your idea could you maybe provide at least the method names. I guess that would give me an idea what you had in mind.

**Comment by alexo** [comment]
Sure, I was thinking about something like: 
```
protected Resource createResource(Element resourceElement);
protected Resource createGroup(Element resourceElement);
```
The default implementation would set the minimize flag based on the provided attribute (as it does now). 
These methods would be invoked from inside of parseResource & parseGroup methods.
