### ISSUE TITLE
Upgrade handlebars processor to latest version 

### ISSUE THREAD

**Issue by msacristan** [wro4j/wro4j#943]
Handlebars is on version 3.0.3. 

When trying to use it with the current preprocesor, it gives out this error when handlebars uses the precompiled templates

Error: Unknown template object: function

...n fileName lineNumber message name number stack".split(" ");d.prototype=Error()

**Comment by alexo** [comment]
@msacristan could you try with latest version 1.7.8?

**Comment by msacristan** [comment]
I updated to 1.7.8 and still got the issue.

**Comment by alexo** [comment]
Could you provide a reproduction path?

**Comment by alexo** [comment]
Duplicate of #964
