### ISSUE TITLE
Memory leak with m2e and maven plugin

### ISSUE THREAD

**Issue by mpiggott** [wro4j/wro4j#950]
I've noticed that repeated builds using m2e (1.6.0) and the maven plugin (1.77) that memory usage continually increases before the IDE eventually hangs.  Looking in the heap dump I see many copies of the same Javascript and CSS files.

Our build has five executions, four with 1 group, one with 7 groups.  We use `ConfigurableWroManagerFactory` and `postProcessors=rubySassCss,yuiCssMin,googleClosureSimple`

**Comment by alexo** [comment]
@mpiggott I'd suspect that this could be a problem with m2e eclipse plugin, rather than with wro4j-maven-plugin...

**Comment by alexo** [comment]
@mpiggott Could you provide some more details, which could be used to reproduce the issue? I'm willing to try analyzing it, but there should be a quick-start project.

**Comment by alexo** [comment]
@mpiggott  Closing this issue with invalid resolution. Feel free to reopen when more details are provided.

**Comment by mpiggott** [comment]
@alexo I believe any wro4j project will exhibit the problem.

I did some debugging and looked at the heap again, I'm wondering if it is related to the use of ThreadLocal in Context as Eclipse executes build jobs in a thread pool.

**Comment by mpiggott** [comment]
Switching to `ro.isdc.wro.extensions.model.factory.SmartWroModelFactory` appears to fix the issue.

**Comment by alexo** [comment]
Which one was used previously? Could you try latest version - 1.7.9?



—
