### ISSUE TITLE
some configuration options in maven pom are ignored

### ISSUE THREAD

**Issue by therob** [wro4j/wro4j#951]
The option `ignoreMissingResources` in Maven POM just changes the output in the Maven log. It works just fine when i set it in the `wro.properties`.
`contextFolder` is also ignored. The Maven log states `[...]/src/main/webapp` at level `INFO` with no additional info. No sign of the configured folder(s) from the POM.

I'm using version 1.7.8 of the Maven-Plugin on Java 8. Let me know if you need more info to reproduce the problem.

**Purpose of this issue:**
Update documentation, so that it would be clear that when ConfigurableWroManagerFactory is used, the configuration options should be provided using wro.properties.

**Comment by therob** [comment]
Ok, the `contextFolder` option works. I had defined two times. But `ignoreMissingResources` is definitely not working.

**Comment by alexo** [comment]
I think that once the ConfigurableWroManagerFactory is used, the configurations defined in pom.xml are overridden with values from wro.properties, also when they are not set by falling back to default values. 

In other words, when using ConfigurableWroManagerFactory, the plugin should be configured through wro.properties only...

**Comment by therob** [comment]
That makes sense to me. It would be nice to have the documentation more specific about that. `ignoreMissingResources` is not mentioned below the `ConfigurableWroManagerFactory`-Section in [1]. Also, thanks for the quick reply!

[1] https://github.com/wro4j/wro4j/blob/1.7.x/docs/ConfigurationOptions.md

**Comment by alexo** [comment]
Agree. I'll change the scope of this issue to update documentation, so that it would clarify current behavior.
