### ISSUE TITLE
Js or Css assets not included randomly

### ISSUE THREAD

**Issue by Veske** [wro4j/wro4j#956]
So I have atleast 150 js files that I include under once group and also a lot of js libraries that I include in another group before it.

The problem is that wro4j seems to decide to randomly not include some files from time to time. For example when doing page refresh and asking server to serve me the assets again, wro4j compiles them together into their respective files and gives them back to me.  No if I look into the files it seems like everything should be there but sometimes it appears that it did not include app.js which is essential for my angular app to even work.   

It does this with style files too but less frequently. In server log I see no errors or exceptions. And logger says that wro4j actually found the files succesfully that are missing.

Does this plugin stop being effective when one group starts getting too big? Could that be the problem?

Here is an example log:
```
-----------------------------------------
ms     %     Task name
-----------------------------------------
00000  000%  Using ro.isdc.wro.model.resource.processor.impl.js.SemicolonAppenderPreProcessor@32bba4fb

16:33:28.555 [wro4j-parallelPreprocessing-4-thread-3] DEBUG r.i.w.m.r.p.d.ProcessorDecorator - Skipping processor: ro.isdc.wro.model.resource.processor.impl.js.JSMinProcessor@77b93cc8
16:33:28.555 [wro4j-parallelPreprocessing-4-thread-3] DEBUG r.i.w.m.r.p.d.ProcessorDecorator - Skipping processor: ro.isdc.wro.model.resource.processor.impl.css.JawrCssMinifierProcessor@51a08a23
16:33:28.555 [wro4j-parallelPreprocessing-4-thread-3] DEBUG r.i.w.m.g.p.PreProcessorExecutor - Callable started for resource: ro.isdc.wro.model.resource.Resource@1614d1f4[JS,/resources/js/app.js,true] ...
16:33:28.555 [wro4j-parallelPreprocessing-4-thread-3] DEBUG r.i.w.m.g.p.PreProcessorExecutor - applying preProcessors: [ro.isdc.wro.model.resource.processor.impl.css.CssUrlRewritingProcessor@3843cf8b, ro.isdc.wro.model.resource.processor.impl.css.CssImportPreProcessor@368436f3, ro.isdc.wro.model.resource.processor.impl.js.SemicolonAppenderPreProcessor@32bba4fb, ro.isdc.wro.model.resource.processor.impl.js.JSMinProcessor@77b93cc8, ro.isdc.wro.model.resource.processor.impl.css.JawrCssMinifierProcessor@51a08a23]
16:33:28.555 [wro4j-parallelPreprocessing-4-thread-3] DEBUG r.i.w.m.r.l.ServletContextUriLocator - locate resource: /resources/js/app.js
16:33:28.555 [wro4j-parallelPreprocessing-4-thread-2] DEBUG r.i.w.m.r.l.s.DispatcherStreamLocator - dispatching request to location: /resources/js/common.js
16:33:28.555 [wro4j-parallelPreprocessing-4-thread-3] DEBUG r.i.w.m.r.l.s.DispatcherStreamLocator - dispatching request to location: /resources/js/app.js
16:33:28.556 [wro4j-parallelPreprocessing-4-thread-1] DEBUG r.i.w.m.r.p.d.BenchmarkProcessorDecorator - StopWatch '': running time (millis) = 3
-----------------------------------------
ms     %     Task name
-----------------------------------------
```

This was the log I got from last time I tried to load my application where app.js was missing.

**Comment by alexo** [comment]
@Veske  could you provide some configuration details? (wro.properties)

**Comment by alexo** [comment]
I assume you have enabled parallel preProcessing. If this is true, disable it - it might be the cause of the problem. Apparently it is not yet reliable enough.

**Comment by Veske** [comment]
```
# https://code.google.com/p/wro4j/wiki/ConfigurationOptions
debug=true
minimizeEnabled=false
resourceWatcherUpdatePeriod=0
cacheUpdatePeriod=30
modelUpdatePeriod=30
parallelPreprocessing=false
preProcessors=
postProcessors=jsMin,cssMin
connectionTimeout=6000
```

looks like this. I just set the parallel option to false. will test it out now.

**Comment by Veske** [comment]
Currently it seems to work better with parallel processing turned off. Will test more for a while and let you know.
