### ISSUE TITLE
How to override properties file

### ISSUE THREAD

**Issue by Veske** [wro4j/wro4j#958]
So by default wro4j will look under WEB-INF for wro.properties file. And in my project I also have that file in there. This file is mostly used when developing on my own machine.

Now when deploying, I want to have a completely separate properties file that would be located somewhere else in the system in some conf folder. 

I belive this is achievable with wro4j-maven-plugin ?
It has a extraConfigFile option under configuration.

But When I specify a new properties file there, I dont see anything in my server log about wro4j looking for it. Also none of the options I specified in there are used.

EDIT: Found some older documentation about it. Seems it should indeed override the default properties file if it exists.

Problem is that wro4j does not want to find the file nor use it according to logs. 
For instance I gave it this path: C:\Users\me\Documents\VM\wro.properties
and nothing happened, it still used the one in the project folder even tough the path I provided exists and also the file in there exists.

**Comment by alexo** [comment]
@Veske could you post the entire configuration (pom.xml and wro.properties)?

**Comment by Veske** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<groups xmlns="http://www.isdc.ro/wro">

	<group name="angular">
		<js>webjar:angular.js</js>
		<js>webjar:angular-sanitize.js</js>
		<js>webjar:ng-grid.js</js>
		<css>webjar:ng-grid.css</css>
		<js>webjar:angular-filter.min.js</js>
		<js>webjar:/js/ngDialog.js</js>
		<css>webjar:/css/ngDialog.css</css>
		<css>webjar:/css/ngDialog-theme-default.css</css>
		<css>webjar:/css/ngDialog-theme-plain.css</css>
	</group>

	<group name="bootstrap">
		<js>/resources/lib/bootstrap/js/bootstrap.js</js>
		<!-- Wro4j has problems with the css when it tries to include bootstrap halflings -->
		<!--<css>/resources/lib/bootstrap/css/bootstrap.css</css>-->
	</group>

	<group name="jquery">
		<js>/resources/lib/jquery/jquery.js</js>
		<js>/resources/lib/jquery/jquery-migrate.js</js>
		<js>/resources/lib/timeentry/*.js</js>
		<css>/resources/lib/timeentry/*.css</css>
		<js>/resources/lib/jqScroll/mwheelIntent.js</js>
		<js>/resources/lib/jqScroll/jquery.jscrollpane.min.js</js>
		<js>/resources/lib/jqScroll/jquery.mousewheel.js</js>
		<css>/resources/lib/jqScroll/jquery.jscrollpane.css</css>
		<js>/resources/lib/jqGrid/**.js</js>
		<css>/resources/lib/jqGrid/**.css</css>
	</group>

	<group name="json2">
		<js>webjar:json2.js</js>
	</group>

	<group name="xeditable">
		<js>webjar:xeditable.js</js>
		<css>webjar:xeditable.css</css>
	</group>

	<!-- Group together all thid-party libraries into one file -->

	<group name="third-party-libs">
		<group-ref>jquery</group-ref>
		<group-ref>json2</group-ref>
		<group-ref>bootstrap</group-ref>
		<group-ref>angular</group-ref>
	</group>

	<group name="controllers">
		<js>/resources/js/controller/**.js</js>
	</group>

	<group name="directives">
		<js minimize="false">/resources/js/directive/**.js</js>
		<css>/resources/js/directive/**.css</css>
	</group>

	<group name="in-house-libs">
		<js>/resources/js/bootstrap-multiselect.js</js>
		<js>/resources/js/multiselect.js</js>
		<js minimize="false">/resources/js/moment-with-langs.js</js>
		<js minimize="false">/resources/js/datetimepicker.js</js>
		<css>/resources/css/datetimepicker.css</css>
		<js minimize="false">/resources/js/dateTimeInput.js</js>
		<js>/resources/js/spin.js</js>
		<js>/resources/js/hitenter.js</js>
		<js>/resources/js/popover.js</js>
		<js>/resources/js/checklist-model.js</js>
	</group>

	<group name="app">
		<js>/resources/js/common.js</js>
		<js>/resources/js/app.js</js>
		<js>/resources/js/ng-factory-common.js</js>
		<css>/resources/css/new-style.css</css>
		<css>/resources/css/style.css</css>
		<css>/resources/css/multiselect.css</css>
		<css>/resources/css/inputselect.css</css>
	</group>

	<!-- Group together our app specific assets -->

	<group name="application">
		<group-ref>in-house-libs</group-ref>
		<group-ref>xeditable</group-ref>
		<group-ref>app</group-ref>
		<group-ref>controllers</group-ref>
		<group-ref>directives</group-ref>
	</group>
</groups>
```

```
<!-- wro4j asset compiler -->
        <dependency>
            <groupId>ro.isdc.wro4j</groupId>
            <artifactId>wro4j-core</artifactId>
			<version>1.7.8</version>
        </dependency>

        <dependency>
            <groupId>ro.isdc.wro4j</groupId>
            <artifactId>wro4j-extensions</artifactId>
			<version>1.7.8</version>
        </dependency>

<plugin>
				<groupId>ro.isdc.wro4j</groupId>
				<artifactId>wro4j-maven-plugin</artifactId>
				<version>1.7.8</version>

				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>

				<configuration>
					<minimize>true</minimize>
					<parallelProcessing>false</parallelProcessing>
					<extraConfigFile>conf/</extraConfigFile>
					<wroFile>src/main/webapp/WEB-INF/wro.xml</wroFile>
					<destinationFolder>src/main/webapp/assets/</destinationFolder>
					<contextFolder>${basedir}/src/main/webapp/WEB-INF</contextFolder>
				</configuration>
			</plugin>
```

**Comment by alexo** [comment]
Could you try the following:
configure a different wroManagerFactory in configuration section:

```
<configuration>
   <wroManagerFactory>ro.isdc.wro.maven.plugin.manager.factory.ConfigurableWroManagerFactory</wroManagerFactory>
</configuration>
``` 
 This one should become the default one, since it really allows overriding the wro.properties location.

**Comment by Veske** [comment]
That seems to work! Is it possible to have a fallback also for this? So that when one folder has this properties file missing then it will look in another one instead?

**Comment by alexo** [comment]
I would lean toward consistency and simplification of configuration. Having one simple way to configure things would eliminate a lot of confusion users have.. 
Of course it is possible to support other types of configurations, but supporting all of them doesn't really scale (time & effort).

**Comment by Veske** [comment]
It's understandable. I just have to accommodate to an edge case that's why the curiosity. Maybe there is just a simple way to extend a class from wro4j to add another properties parameter for another extra config?

**Comment by alexo** [comment]
What is your use-case?

**Comment by Veske** [comment]
When deploying the application, the sys-admins need the properties to be in a centralized folder on an UNIX system. When not deploying, the file has to be in git tree but also in a set folder that is used for all other properties as well and which sadly is not under WEB-INF.

**Comment by alexo** [comment]
What about configuring path and pointing it to a symlink which can be changed dynamically based on your environment?

**Comment by Veske** [comment]
Could work. Will have to try it out.

**Comment by alexo** [comment]
Closing this issue with 'WONTFIX' resolution, since there is a workaround available. If you don't agree, feel free to reopen it.

**Comment by Veske** [comment]
Yes it seems that would not work too. The project it self is built with Jenkins so at that moment the wro.properties file does not exists yet. When the application is deployed and launched, then we usually read in all the properties with Spring annotations and then use them.

**Comment by alexo** [comment]
The maven plugin is invoked during the build time. I don't think I understand the problem.

You could extend the ConfigurableWroManagerFactory and override the createProperties method. This is the place where the wro.properties is loaded.

**Comment by Veske** [comment]
You mean ServletContextPropertyWroConfigurationFactory?  the create properties method seems to be there.

**Comment by alexo** [comment]
This is the implementation fo [ConfigurableWroManagerFactory](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/manager/factory/ConfigurableWroManagerFactory.java). You can see that the WroConfiguration is initialized there. 
You could implement a custom initialization logic by extending it.

**Comment by Veske** [comment]
Hmm,  the way I have it included in maven currently shows only the ConfigurableWroManagerFactory from wro4j-core. I have wro4j included as a dependency and the maven plugin as a plugin for build time.

**Comment by Veske** [comment]
I understand that the wro4j-maven-plugin has to be declared as a <plugin> in maven but declaring it like that makes it impossible to access the classes in that library from our own source. So I cannot extend the wro4j-maven-plugin. I can only extend the wro4j-core which is a different thing.

**Comment by alexo** [comment]
It shouldn't be a problem. Just extend the [ConfigurableWroManagerFactory](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-maven-plugin/src/main/java/ro/isdc/wro/maven/plugin/manager/factory/ConfigurableWroManagerFactory.java) and configure it in <configuration> section of the maven plugin declaration.

**Comment by Veske** [comment]
But lets say that I disable the plugin all together now and extend the ConfigurableWroManagerFactory in wro4j core. Where should it be declared that wro4j should use it when application is launched?

I attempted to include it in web.xml following some old documentation you had but that seems to not work.

**Comment by alexo** [comment]
@Veske  could you join [gitter](https://gitter.im/wro4j/wro4j) ?
