### ISSUE TITLE
lessCssImport removing important parts from import files

### ISSUE THREAD

**Issue by ggtools** [wro4j/wro4j#960]
I discover a strange issue while trying to use wro4j with the less version of bootstrap.

In a nutshell it seems that the `lessCssImport` pre-processor consider some parts of the imported files as *commented out*. The configuration is quite tricky to achieve but can be reproduced with a simple setup.

I have two files, `main.less` and `second.less`:

```
/*!
 * Comment
 */
@import "second.less";
```

```
//** Test.

@nice-blue: #5B83AD;
@light-blue: @nice-blue + #111;

#header {
  color: @light-blue;
}
```

The `wro.properties` only contain one line: `preProcessors=lessCssImport`. 

As such I would expect to have only a `wro.css` file containing the directives from `second.less` (not converted to css since I didn't put the less post processor). Instead I get the following file:

```
/


```

I use Maven with the following configuration:

```
            <plugin>
                <groupId>ro.isdc.wro4j</groupId>
                <artifactId>wro4j-maven-plugin</artifactId>
                <version>1.7.8</version>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <wroManagerFactory>ro.isdc.wro.maven.plugin.manager.factory.ConfigurableWroManagerFactory
                    </wroManagerFactory>
                    <destinationFolder>${basedir}/target/generated-resources/static/</destinationFolder>
                    <wroFile>${basedir}/src/main/wro/wro.xml</wroFile>
                    <extraConfigFile>${basedir}/src/main/wro/wro.properties</extraConfigFile>
                </configuration>
            </plugin>
```

**Comment by alexo** [comment]
@ggtools  Could you try with "less4j" processor?

**Comment by ggtools** [comment]
Yes it works with less4j as preprocessor. Interesting. Thanks
