### ISSUE TITLE
Support Wildcards when using Webjars

### ISSUE THREAD

**Issue by oers** [wro4j/wro4j#972]
Instead of having to define the version two times (in the pom and the wro.xml) let me accept any version.

Instead of:
{code}
<js minimize="false">webjar:angularjs/1.4.3/i18n/angular-locale_de-at.js</js>
{code}

I would like to write:
{code}
<js minimize="false">webjar:angularjs/*/i18n/angular-locale_de-at.js</js>
{code}

**Comment by alexo** [comment]
Actually, the webjar uri doesn't require the full path (including version). 
If you want to use wildcard for webjar resources (meaning you want to include all resources located inside a particular folder or sub-folder), you can use the classpath uri instead (example: classpath:angularjs/*/i18n/angular-locale_de-at.js)

**Comment by oers** [comment]
classpath does not seem to work (I just changed webjar to classpath):

```java
Caused by: java.io.IOException: Couldn't get InputStream from this resource: classpath:angularjs/*/i18n/angular-locale_de-at.js
	at ro.isdc.wro.model.resource.locator.ClasspathUriLocator.locate(ClasspathUriLocator.java:95)
```

**Comment by alexo** [comment]
When using classpath uri, you should provide fully qualified resource name. An example that should work:

    <js>classpath:META-INF/resources/webjars/angularjs/1.4.3/i18n/*.js</js>

Currently, wildcard cannot be used to search for a variable subfolder name, like this:

    <js>classpath:META-INF/resources/webjars/angularjs/*/i18n/*.js</js>

If you find it useful to have this feature, consider opening an issue.

**Comment by oers** [comment]
Yes the subfolder part would be very useful. So that versions (subfolders) need not to be declared twice (once in the maven plugin dependency and once in wro4j.xml).
Where should I open this issue (is this not the right place)?

**Comment by alexo** [comment]
This is the right place. But it is better to not mix different requirements. If you want to support subfolders, it is not related to webjars (but to classpath locator). 

The webjar uri itself, allows you to not specify the library version, so you could do something like:

    webjar:i18n/angular-locale_de-at.js

But using webjar uri doesn't allow using wildcards yet.

**Comment by oers** [comment]
The last hint "fixed" my problems and I think it is enough to fit my needs. Declaring dependencies like this:
```xml
    <js minimize="false">webjar:angular.min.js</js>
    <js minimize="false">webjar:angular-resource.min.js</js>
    <js minimize="false">webjar:angular-route.min.js</js>
    <js minimize="false">webjar:ui-bootstrap.min.js</js>
    <js minimize="false">webjar:ui-bootstrap-tpls.min.js</js>
    <js minimize="false">webjar:angular-locale_de-at.js</js>
```

is enough. I always thought it needed complete paths.
I will close this issue.
Thank you very much for your input!.
