### ISSUE TITLE
CssImportPreProcessor mishandle //** comments

### ISSUE THREAD

**Issue by alexo** [wro4j/wro4j#976]
If the input less file contains `//** blah` style comment, the `removeImportsFromComments` method of `CssImportInspector` removes everything between it and closest `*/`. 

Simple example less:
````
//** deleting the comment removes the problem
@body-bg:               #fff;

/**
 * deleting the comment removes the problem
 */
@import  "variables.less";
@mainColor: blue;
 
h1,h2,h3,h4,h5,h6,h7,h8 {
	color: @mainColor;
	font-weight: normal;
}
````

is transformed into syntactically incorrect:
````
/
@import  "variables.less";
@mainColor: blue;
 
h1,h2,h3,h4,h5,h6,h7,h8 {
	color: @mainColor;
	font-weight: normal;
}
````

Context: attempts to import variables.less file from bootstrap and compile the result using wro4j leads to compile error in less4j https://github.com/SomMeri/less4j/issues/208 . 

**Note**: this issue was migrated from https://github.com/alexo/wro4j/issues/187

**Comment by M3lkior** [comment]
Very Nice Alexo, Thanks :)
