### ISSUE TITLE
CssMinProcessor.process input file parsing is wrong

### ISSUE THREAD

**Issue by yasserzamani** [wro4j/wro4j#994]
From first of the correct input file, it converts
> @-webkit-keyframes borderPulse{15%{opacity:1}100%{-webkit-transform:scale(1.3);opacity:0}}

to following wrong syntax
> 100%{-webkit-transform:scale(1.3);opacity:0;}

I reviewed source code and it seems it **cannot** parse ***multi-level internal { and }s***.

**Comment by alexo** [comment]
CssMin processor is quite outdated. I would suggest using cssMinJawr or yuiCssMin

**Comment by yasserzamani** [comment]
Thank you very much. **cssMinJawr** parsing is correct!

**Comment by alexo** [comment]
Adding wontfix resolution, since there is no point  maintaining an obsolete processor which can be replaced easily with another one.
